In [88]:
import pickle

In [89]:
node2id = pickle.load(open('data/aida/node2ind_train.pkl', 'rb'))

In [90]:
id2node = pickle.load(open('data/aida/ind2node_train.pkl', 'rb'))

In [91]:
# extract first 10 nodes from node2id dict
topNodes = {k: node2id[k] for k in list(node2id)[:10]}

In [92]:
topNodes

{rdflib.term.URIRef('http://aida.kmi.open.ac.uk/resource/1480305125'): 4517,
 rdflib.term.URIRef('http://cso.kmi.open.ac.uk/topics/multicasts'): 97791,
 rdflib.term.URIRef('http://aida.kmi.open.ac.uk/resource/2228819592'): 1,
 rdflib.term.URIRef('http://aida.kmi.open.ac.uk/ontology#author'): 98292,
 rdflib.term.URIRef('http://aida.kmi.open.ac.uk/resource/2652442014'): 2,
 rdflib.term.Literal('廖云沼'): 2,
 rdflib.term.URIRef('http://aida.kmi.open.ac.uk/resource/2833184094'): 3,
 rdflib.term.URIRef('http://makg.org/entity/2833184094'): 3,
 rdflib.term.URIRef('http://aida.kmi.open.ac.uk/resource/1481284503'): 4,
 rdflib.term.URIRef('http://cso.kmi.open.ac.uk/topics/communication_systems'): 98283}

In [93]:
import torch

# load the embeddings
embeddings = torch.load('models/transe_emb.pt')
print(embeddings.shape)

torch.Size([98303, 50])


In [94]:
# print first 10 embeddings
topEmbeddings = embeddings[:10]
topEmbeddings

tensor([[-6.0047e-01, -1.5493e+00,  1.8409e+00,  8.8067e-01,  2.5927e-02,
         -6.9131e-02,  1.1357e-01, -1.0175e+00, -2.3915e-01,  1.5683e+00,
          5.1388e-02, -1.0667e-01,  1.1218e+00, -3.5441e-03, -1.4871e+00,
          8.3106e-02,  4.7619e-02,  1.9909e+00, -1.5791e-01,  7.1899e-02,
          1.8043e+00, -2.0493e+00, -1.3852e-03, -3.3051e-02, -1.1820e-01,
          2.8002e-01, -3.2873e-02, -4.5883e-02, -5.5302e-02,  8.3398e-02,
         -3.6560e-02, -3.2438e-01,  2.7757e-01,  6.4529e-01, -6.6381e-01,
         -2.2786e-01,  2.0015e+00, -3.0889e-01,  1.7998e-03, -1.6845e+00,
         -1.5232e+00, -7.9554e-02, -2.6275e-02, -4.0446e-01,  5.6496e-01,
          1.6133e-02, -4.6288e-02,  1.1914e-01,  5.1178e-02, -9.6689e-02],
        [-9.6613e-02,  9.1172e-01, -3.2575e-01, -3.9009e-02,  2.4128e-03,
          1.7235e-01,  2.9823e-01, -9.8329e-02,  6.7461e-02, -1.2933e+00,
          5.5526e-01,  7.2430e-02,  1.5448e+00, -9.4464e-02, -9.0229e-02,
          1.6211e+00,  3.8709e-02, -1

In [95]:
train_data = pickle.load(open('data/aida/test0_1_train_graph.pkl', 'rb'))

In [96]:
import numpy as np

# filter embeddings by edge type and choose first 20 samples
name_idx = np.where(train_data.edge_type == 4)[0]
name_idx_100 = name_idx[:100]
name_idx_100

array([  30,   43,  182,  253,  259,  309,  367,  493,  509,  681,  697,
        747,  755,  841,  864,  867,  966,  980, 1071, 1100, 1145, 1207,
       1247, 1353, 1391, 1431, 1522, 1644, 1815, 2000, 2193, 2253, 2448,
       2488, 2593, 2669, 2687, 2780, 2857, 2886, 2958, 2969, 3028, 3038,
       3092, 3432, 3518, 3776, 3790, 3795, 3819, 3821, 3829, 3990, 4003,
       4008, 4231, 4366, 4468, 4508, 4572, 4703, 4747, 4847, 4861, 4880,
       4941, 5054, 5100, 5174, 5343, 5486, 5528, 5573, 5838, 5899, 5934,
       6028, 6052, 6067, 6078, 6180, 6286, 6291, 6360, 6473, 6496, 6552,
       6591, 6607, 6624, 6727, 6784, 6793, 6847, 6998, 7214, 7280, 7286,
       7332])

In [97]:
# convert to list of nodes
for idx in name_idx:
    print(id2node[idx])

fuzzy based dynamic load balancing scheme for efficient edge server selection in cloud oriented content delivery network using voronoi diagram
method for sharing data among mobile terminals system and control server
positive backstitching driving mechanism of roller wheel pressing foot of sewing machine
student outcomes assessment methodology for abet accreditation a case study of computer science and computer information systems programs
a new hmm training and testing scheme
portable paper archive file storage device
geese pso optimization in geometric constraint solving
software operating method and device and terminal
chip resistor detects flow device
educational aspects of business simulation softwares
systems and methods for allowing a user to control their computing environment within a virtual computing environment
an efficient algorithm of performing range analysis for fixed point arithmetic circuits based on sat checking
information processing apparatus control method and prog

In [98]:
# create index dictionary for titles
title2id = {id2node[idx]: i for i, idx in enumerate(name_idx)}
id2title = {i: id2node[idx] for i, idx in enumerate(name_idx)}

In [99]:
len(title2id)

1554

## Paper

In [100]:
import rdflib

query_result = 'http://aida.kmi.open.ac.uk/resource/2626778328'  
q_res = 'method of chinese word segmentation based on character word classification'
q_res1 = 'hardware architecture for finding shortest paths'
q_res2 = 'light incorporating a clip and bottle opener'
q_res3 = 'a non revisiting particle swarm optimization'
q = rdflib.term.Literal(q_res3)


In [101]:
# find the index of the query result
query_idx = node2id[q]
query_idx

12280

In [102]:
# find the embedding of the query result
query_emb = embeddings[query_idx]
query_emb

tensor([-1.6178, -1.1462, -0.1500,  0.6462,  0.0312,  1.1916,  0.1345, -0.1341,
         1.2846, -0.0689,  0.3198, -0.1241,  1.6320,  0.0584,  0.7360, -0.7350,
         0.3187,  0.0522, -0.0492,  0.4365,  1.5141,  0.5126,  0.1305,  2.0112,
         0.2158,  1.7819, -0.0305, -1.8188,  0.0762,  0.2058, -0.0809,  0.0298,
         0.0508,  0.0668, -2.1175, -1.7329,  0.0324, -0.6859, -0.0944,  0.0236,
        -0.3041,  0.0462, -0.0811, -2.1163,  0.1039,  0.3003, -0.0887,  0.8729,
         0.1155, -0.1246], device='cuda:0')

In [103]:
name_idx = np.where(train_data.edge_type == 4)[0]

In [104]:
# subset of embeddings consisting of only the title nodes
title_emb = embeddings[name_idx]

In [105]:
title_emb.shape

torch.Size([1554, 50])

In [106]:
def dot_product_similarity(query_emb, title_emb):
    return np.dot(query_emb, title_emb.T)

In [107]:
# find the embeddings of the node that are in close proximity to the query result
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances, manhattan_distances

# calculate the cosine similarity between the query result and all other nodes
dot_product_sim = dot_product_similarity(query_emb.reshape(1, -1).cpu(), title_emb.cpu())
# rank the nodes by similarity
ranked_idx = np.argsort(dot_product_sim[0])[::-1]
# print the top 10 nodes
ranked_idx = [(i, dot_product_sim[0][i]) for i in ranked_idx]
ranked_idx[1:11]

[(1232, 18.83144),
 (1217, 17.383738),
 (882, 17.353466),
 (267, 16.452759),
 (11, 16.137836),
 (233, 16.029955),
 (1001, 15.269769),
 (439, 15.210283),
 (1478, 14.2943125),
 (734, 14.292408)]

In [108]:
# print the top 10 nodes
for idx in ranked_idx[1:51]:
    print(id2title[idx[0]], ": ", idx[1])

mergers and acquisitions management new directions editorial :  18.83144
simple garbage bag bracket :  17.383738
image processor and image display :  17.353466
on the reversibility of live equal conflict petri nets :  16.452759
an efficient algorithm of performing range analysis for fixed point arithmetic circuits based on sat checking :  16.137836
task scheduling in the cloud computing based on the cuckoo search algorithm :  16.029955
an offer system for the entrance exam based on wireless internet :  15.269769
method for identifying logical data discrepancies between database replicas in a database cluster :  15.210283
developing an ontology for cyber security knowledge graphs :  14.2943125
research data supporting semantically conditioned lstm based natural language generation for spoken dialogue systems :  14.292408
anonymous id based group key agreement for wireless networks :  13.988954
digital tourism integrated service system realization :  13.653151
intelligent type household 

In [109]:
# find the embeddings of the node that are in close proximity to the query result
# calculate the cosine similarity between the query result and all other nodes
manhattan_distance = manhattan_distances(query_emb.reshape(1, -1).cpu(), title_emb.cpu())
# rank the nodes by similarity
ranked_idx = np.argsort(manhattan_distance.flatten())
# print the top 10 nodes
ranked_idx = [(i, manhattan_distance[0][i]) for i in ranked_idx]
ranked_idx[1:11]

[(327, 26.60618481133133),
 (185, 27.269826508301776),
 (326, 27.320744274184108),
 (882, 27.484722226392478),
 (1217, 27.54701428115368),
 (267, 28.65608301293105),
 (1082, 28.874116509221494),
 (233, 28.886884087580256),
 (1371, 28.993591765873134),
 (1090, 29.36920327032567)]

In [110]:
# print the top 10 nodes
for idx in ranked_idx[1:51]:
    print(id2title[idx[0]], ": ", idx[1])

relation between joint optimizations for multiuser mimo uplink and downlink with imperfect csi :  26.60618481133133
a modified membrane inspired algorithm based on particle swarm optimization for mobile robot path planning :  27.269826508301776
integrating schemas of heterogeneous relational databases through schema matching :  27.320744274184108
image processor and image display :  27.484722226392478
simple garbage bag bracket :  27.54701428115368
on the reversibility of live equal conflict petri nets :  28.65608301293105
interference cancellation in multiuser acoustic underwater networks using probabilistic sdma :  28.874116509221494
task scheduling in the cloud computing based on the cuckoo search algorithm :  28.886884087580256
intuitionistic fuzzy segmentation of medical images :  28.993591765873134
towards a sdn based architecture for analyzing network traffic in cloud computing infrastructures :  29.36920327032567
open chinese entity relation extraction method using dependency a

In [111]:
# find the embeddings of the node that are in close proximity to the query result
# calculate the cosine similarity between the query result and all other nodes
cosine_sim = cosine_similarity(query_emb.reshape(1, -1).cpu(), title_emb.cpu())
# rank the nodes by similarity
ranked_idx = np.argsort(cosine_sim[0])[::-1]
# add the cosine similarity to the ranked nodes
ranked_idx = [(i, cosine_sim[0][i]) for i in ranked_idx]
ranked_idx[1:11]

[(267, 0.49472785),
 (1217, 0.49390805),
 (1232, 0.49175948),
 (882, 0.4813009),
 (327, 0.47264177),
 (439, 0.46276903),
 (233, 0.44511554),
 (11, 0.44076052),
 (1082, 0.42433304),
 (15, 0.40814137)]

In [112]:
# print the top 10 nodes
for idx in ranked_idx[1:51]:
    print(id2title[idx[0]], ": ", idx[1])

on the reversibility of live equal conflict petri nets :  0.49472785
simple garbage bag bracket :  0.49390805
mergers and acquisitions management new directions editorial :  0.49175948
image processor and image display :  0.4813009
relation between joint optimizations for multiuser mimo uplink and downlink with imperfect csi :  0.47264177
method for identifying logical data discrepancies between database replicas in a database cluster :  0.46276903
task scheduling in the cloud computing based on the cuckoo search algorithm :  0.44511554
an efficient algorithm of performing range analysis for fixed point arithmetic circuits based on sat checking :  0.44076052
interference cancellation in multiuser acoustic underwater networks using probabilistic sdma :  0.42433304
anonymous id based group key agreement for wireless networks :  0.40814137
research data supporting semantically conditioned lstm based natural language generation for spoken dialogue systems :  0.40518123
a modified membrane 

In [113]:
# find the embeddings of the node that are in close proximity to the query result
# calculate the cosine similarity between the query result and all other nodes
euclid_sim = euclidean_distances(query_emb.reshape(1, -1).cpu(), title_emb.cpu())
# rank the nodes by similarity
ranked_idx = np.argsort(euclid_sim[0])
# add the cosine similarity to the ranked nodes
ranked_idx = [(i, euclid_sim[0][i]) for i in ranked_idx]
ranked_idx[1:11]

[(327, 5.518166),
 (1082, 5.827957),
 (267, 5.854251),
 (185, 5.9183106),
 (1090, 5.957182),
 (376, 5.9820433),
 (1217, 5.9897738),
 (439, 6.0072517),
 (490, 6.02803),
 (952, 6.0691147)]

In [114]:
# print the top 10 nodes
for idx in ranked_idx[1:51]:
    print(id2title[idx[0]], ": ", idx[1])

relation between joint optimizations for multiuser mimo uplink and downlink with imperfect csi :  5.518166
interference cancellation in multiuser acoustic underwater networks using probabilistic sdma :  5.827957
on the reversibility of live equal conflict petri nets :  5.854251
a modified membrane inspired algorithm based on particle swarm optimization for mobile robot path planning :  5.9183106
towards a sdn based architecture for analyzing network traffic in cloud computing infrastructures :  5.957182
impairment aware routing and wavelength assignment in translucent networks state of the art :  5.9820433
simple garbage bag bracket :  5.9897738
method for identifying logical data discrepancies between database replicas in a database cluster :  6.0072517
open chinese entity relation extraction method using dependency analysis :  6.02803
technical objects in the biological century :  6.0691147
image processor and image display :  6.1266503
power allocation strategy for cognitive radio t

## Institution

In [115]:
import numpy as np

# filter embeddings by edge type and choose first 20 samples
name_idx = np.where(train_data.edge_type == 14)[0]
name_idx_100 = name_idx[:100]
name_idx_100

array([  860,  2937,  3591,  8084, 13010, 13448, 13842, 16143, 17078,
       17814, 20487, 21675, 24150, 25045, 30920, 33371, 33801, 35996,
       38221, 39014, 41464, 44323, 46905, 50535, 51894, 52083, 52497,
       53869, 55076, 55634, 56383, 58699, 62713, 64687, 67656, 68272,
       80432, 84573, 87937, 90054, 92302, 92715, 93521, 96484, 97479])

In [116]:
# convert to list of nodes
for idx in name_idx:
    print(id2node[idx])

rothamsted research
pantheon-sorbonne university
university of applied sciences mainz
conexant (united states)
biogen (united states)
university of canterbury
henkel (germany)
university of agriculture faisalabad
dalian jiaotong university
prince george's community college
sweet briar college
university of maine
university medical center freiburg
university of kansas hospital
czech education and scientific net work
uludağ university
royal military academy
king mongkut's institute of technology ladkrabang
aeronautical development agency
dongyang mirae university
ionian university
john radcliffe hospital
dalian maritime university
vrvis (austria)
new zealand college of chiropractic
sequans communications (united kingdom)
university of indianapolis
bahçeşehir university
university of tehran
benedictine university
university of technology- iraq
yanbian university
institut des nanotechnologies de lyon
suzhou university of science and technology
daido university
the university of texas at sa